import type {
  AnalyticsSummary,
  AuditSubmission,
  DateRange,
  FunnelStepSummary,
  Lead,
  LeadEvent,
  LeadNote,
  LeadOwner,
  MetricSummary,
  PipelineStageSummary,
  SourceSummary,
} from './types';

export const dashboardNow = '2026-07-07T10:00:00.000Z';

export const defaultDashboardDateRange: DateRange = {
  key: '7d',
  label: 'Last 7 days',
  from: '2026-07-01T00:00:00.000Z',
  to: dashboardNow,
};

export const dashboardDateRanges: DateRange[] = [
  defaultDashboardDateRange,
  {
    key: '14d',
    label: 'Last 14 days',
    from: '2026-06-24T00:00:00.000Z',
    to: dashboardNow,
  },
  {
    key: '30d',
    label: 'Last 30 days',
    from: '2026-06-08T00:00:00.000Z',
    to: dashboardNow,
  },
  {
    key: '90d',
    label: 'Last 90 days',
    from: '2026-04-08T00:00:00.000Z',
    to: dashboardNow,
  },
];

export const leadOwners: LeadOwner[] = [
  {
    id: 'owner-ava',
    name: 'Ava Sinclair',
    initials: 'AS',
    role: 'Founder ops',
  },
  {
    id: 'owner-malik',
    name: 'Malik West',
    initials: 'MW',
    role: 'Growth lead',
  },
  {
    id: 'owner-ines',
    name: 'Ines Parker',
    initials: 'IP',
    role: 'Solutions lead',
  },
];

export const leads: Lead[] = [
  {
    id: 'lead-northstar',
    created_at: '2026-07-07T07:18:00.000Z',
    updated_at: '2026-07-07T09:28:00.000Z',
    name: 'Maya Chen',
    email: 'maya.chen@northstarops.co',
    company: 'Northstar Ops',
    website: 'https://northstarops.co',
    status: 'qualified',
    source: 'home_hero_form',
    owner_user_id: 'owner-ava',
    last_contacted_at: null,
    qualification_score: 94,
  },
  {
    id: 'lead-aurora',
    created_at: '2026-07-06T15:42:00.000Z',
    updated_at: '2026-07-07T08:05:00.000Z',
    name: 'Ethan Rhodes',
    email: 'ethan@auroraledger.com',
    company: 'Aurora Ledger',
    website: 'https://auroraledger.com',
    status: 'scheduled',
    source: 'navbar_audit',
    owner_user_id: 'owner-ines',
    last_contacted_at: '2026-07-06T17:02:00.000Z',
    qualification_score: 88,
  },
  {
    id: 'lead-halo',
    created_at: '2026-07-05T10:14:00.000Z',
    updated_at: '2026-07-05T10:14:00.000Z',
    name: 'Priya Raman',
    email: 'priya@halomaterials.com',
    company: 'Halo Materials',
    website: 'https://halomaterials.com',
    status: 'new',
    source: 'selected_work_card',
    owner_user_id: null,
    last_contacted_at: null,
    qualification_score: 79,
  },
  {
    id: 'lead-meridian',
    created_at: '2026-07-04T08:20:00.000Z',
    updated_at: '2026-07-06T12:40:00.000Z',
    name: 'Jon Bell',
    email: 'jon@meridianclinicgroup.com',
    company: 'Meridian Clinic Group',
    website: 'https://meridianclinicgroup.com',
    status: 'contacted',
    source: 'book_call_page',
    owner_user_id: 'owner-malik',
    last_contacted_at: '2026-07-04T12:24:00.000Z',
    qualification_score: 72,
  },
  {
    id: 'lead-sable',
    created_at: '2026-07-03T19:12:00.000Z',
    updated_at: '2026-07-06T16:11:00.000Z',
    name: 'Lina Ortega',
    email: 'lina@sableatelier.com',
    company: 'Sable Atelier',
    website: 'https://sableatelier.com',
    status: 'proposal_ready',
    source: 'audit_success',
    owner_user_id: 'owner-ava',
    last_contacted_at: '2026-07-06T15:45:00.000Z',
    qualification_score: 91,
  },
  {
    id: 'lead-civic',
    created_at: '2026-07-02T11:32:00.000Z',
    updated_at: '2026-07-02T11:32:00.000Z',
    name: 'Noah Grant',
    email: 'noah@civicforge.io',
    company: 'Civic Forge',
    website: 'https://civicforge.io',
    status: 'qualified',
    source: 'pricing_page',
    owner_user_id: null,
    last_contacted_at: null,
    qualification_score: 84,
  },
  {
    id: 'lead-peakline',
    created_at: '2026-06-30T14:05:00.000Z',
    updated_at: '2026-07-05T09:20:00.000Z',
    name: 'Sara McNeil',
    email: 'sara@peaklinecapital.co',
    company: 'Peakline Capital',
    website: 'https://peaklinecapital.co',
    status: 'won',
    source: 'solution_page',
    owner_user_id: 'owner-ines',
    last_contacted_at: '2026-07-05T09:20:00.000Z',
    qualification_score: 96,
  },
  {
    id: 'lead-lattice',
    created_at: '2026-06-29T13:46:00.000Z',
    updated_at: '2026-07-02T16:30:00.000Z',
    name: 'Ben Okafor',
    email: 'ben@latticehire.com',
    company: 'Lattice Hire',
    website: 'https://latticehire.com',
    status: 'lost',
    source: 'industry_page',
    owner_user_id: 'owner-malik',
    last_contacted_at: '2026-07-01T10:10:00.000Z',
    qualification_score: 63,
  },
  {
    id: 'lead-verdant',
    created_at: '2026-06-27T16:08:00.000Z',
    updated_at: '2026-07-01T13:18:00.000Z',
    name: 'Nora Silva',
    email: 'nora@verdantsupply.com',
    company: 'Verdant Supply',
    website: 'https://verdantsupply.com',
    status: 'archived',
    source: 'footer_audit',
    owner_user_id: 'owner-ava',
    last_contacted_at: '2026-06-28T09:41:00.000Z',
    qualification_score: 41,
  },
];

export const auditSubmissions: AuditSubmission[] = [
  {
    id: 'audit-northstar-full',
    lead_id: 'lead-northstar',
    created_at: '2026-07-07T07:21:00.000Z',
    submission_type: 'full_audit',
    source: 'home_hero_form',
    project_type: 'Revenue operations system',
    industry_segment: 'B2B services',
    system_status: 'Manual handoffs across sales, delivery, and finance',
    problems:
      'Inbound leads are being qualified in spreadsheets, then copied into three tools before delivery sees the context.',
    improve_first:
      'Centralize intake, scoring, and handoff logic before rebuilding reporting. The operational leak is happening before the proposal stage.',
    budget_range: '$45k to $75k',
    timeline: '30 to 60 days',
    decision_stage: 'Founder approved scope',
    preferred_next_step: 'Private working session',
    extra_context:
      'They want a system that can support a new partner channel launching in August.',
    raw_payload: { submission_version: 'v1', steps_completed: 6 },
  },
  {
    id: 'audit-aurora-full',
    lead_id: 'lead-aurora',
    created_at: '2026-07-06T15:45:00.000Z',
    submission_type: 'full_audit',
    source: 'navbar_audit',
    project_type: 'Client portal and onboarding',
    industry_segment: 'Fintech',
    system_status: 'Portal exists but onboarding is still managed through email threads',
    problems:
      'Enterprise clients wait too long between contract signing and first value.',
    improve_first:
      'Replace manual onboarding tasks with a staged portal and internal control board.',
    budget_range: '$75k to $120k',
    timeline: 'This quarter',
    decision_stage: 'Evaluating implementation partners',
    preferred_next_step: 'Book a call',
    extra_context:
      'Security review is important, but they are ready to start discovery now.',
    raw_payload: { submission_version: 'v1', steps_completed: 6 },
  },
  {
    id: 'audit-halo-quick',
    lead_id: 'lead-halo',
    created_at: '2026-07-05T10:14:00.000Z',
    submission_type: 'quick_start',
    source: 'selected_work_card',
    project_type: 'Inventory planning workflow',
    industry_segment: 'Manufacturing',
    system_status: 'Forecasting is split across Airtable and emails',
    problems: 'Leadership cannot see when supplier delays will affect booked orders.',
    improve_first:
      'Start with an exception dashboard for supply risk and order commitments.',
    budget_range: '$25k to $45k',
    timeline: '60 to 90 days',
    decision_stage: 'Problem defined',
    preferred_next_step: 'Send audit recommendation',
    extra_context: 'They clicked through from the selected work case study twice.',
    raw_payload: { submission_version: 'v1', steps_completed: 2 },
  },
  {
    id: 'audit-meridian-full',
    lead_id: 'lead-meridian',
    created_at: '2026-07-04T08:23:00.000Z',
    submission_type: 'full_audit',
    source: 'book_call_page',
    project_type: 'Multi-location scheduling system',
    industry_segment: 'Healthcare services',
    system_status: 'Scheduling and patient follow-up are handled in separate systems',
    problems:
      'Clinic managers are losing referral visibility after the first appointment.',
    improve_first:
      'Map referral intake to scheduling outcomes and close the handoff loop.',
    budget_range: '$45k to $75k',
    timeline: '90 days',
    decision_stage: 'Comparing build options',
    preferred_next_step: 'Book a call',
    extra_context: 'They need a practical plan before the September location opening.',
    raw_payload: { submission_version: 'v1', steps_completed: 6 },
  },
  {
    id: 'audit-sable-full',
    lead_id: 'lead-sable',
    created_at: '2026-07-03T19:18:00.000Z',
    submission_type: 'full_audit',
    source: 'audit_success',
    project_type: 'Premium commerce operations',
    industry_segment: 'Luxury retail',
    system_status: 'High-touch sales team is working around the commerce backend',
    problems:
      'VIP client preferences and made-to-order timelines are not visible in fulfillment.',
    improve_first:
      'Create a clienteling and fulfillment control layer before replacing commerce.',
    budget_range: '$120k plus',
    timeline: 'This quarter',
    decision_stage: 'Ready for proposal',
    preferred_next_step: 'Proposal review',
    extra_context: 'Founder wants the first phase live before the autumn collection.',
    raw_payload: { submission_version: 'v1', steps_completed: 6 },
  },
  {
    id: 'audit-civic-quick',
    lead_id: 'lead-civic',
    created_at: '2026-07-02T11:32:00.000Z',
    submission_type: 'quick_start',
    source: 'pricing_page',
    project_type: 'Grant reporting workflow',
    industry_segment: 'Public sector software',
    system_status: 'Customer success exports data manually for each reporting cycle',
    problems: 'Grant reporting creates a two-week support spike every month.',
    improve_first: 'Automate reporting packs and expose customer-ready progress views.',
    budget_range: '$25k to $45k',
    timeline: '30 to 60 days',
    decision_stage: 'Budget owner involved',
    preferred_next_step: 'Send audit recommendation',
    extra_context:
      'No owner assigned yet, but the score is above the qualification line.',
    raw_payload: { submission_version: 'v1', steps_completed: 2 },
  },
  {
    id: 'audit-peakline-full',
    lead_id: 'lead-peakline',
    created_at: '2026-06-30T14:12:00.000Z',
    submission_type: 'full_audit',
    source: 'solution_page',
    project_type: 'Investor reporting platform',
    industry_segment: 'Private capital',
    system_status: 'Quarterly reports are produced by analysts with manual data pulls',
    problems:
      'Reporting quality is strong, but turnaround time is limiting new fund capacity.',
    improve_first: 'Create a secure reporting workspace with analyst review controls.',
    budget_range: '$120k plus',
    timeline: 'This quarter',
    decision_stage: 'Contract signed',
    preferred_next_step: 'Kickoff',
    extra_context: 'Won from a warm referral after seeing the systems audit page.',
    raw_payload: { submission_version: 'v1', steps_completed: 6 },
  },
  {
    id: 'audit-lattice-quick',
    lead_id: 'lead-lattice',
    created_at: '2026-06-29T13:46:00.000Z',
    submission_type: 'quick_start',
    source: 'industry_page',
    project_type: 'Hiring workflow repair',
    industry_segment: 'HR technology',
    system_status: 'Applicant tracking is fine, but executive reporting is missing',
    problems: 'The team needs board visibility, not a full system rebuild.',
    improve_first: 'Scope a reporting layer before considering platform changes.',
    budget_range: '$10k to $25k',
    timeline: 'Later this year',
    decision_stage: 'Researching',
    preferred_next_step: 'Send audit recommendation',
    extra_context: 'Not a fit for the current premium build threshold.',
    raw_payload: { submission_version: 'v1', steps_completed: 2 },
  },
];

export const leadEvents: LeadEvent[] = [
  {
    id: 'event-northstar-audit',
    lead_id: 'lead-northstar',
    created_at: '2026-07-07T07:21:00.000Z',
    event_type: 'audit_submitted',
    source: 'home_hero_form',
    metadata: {
      project_type: 'Revenue operations system',
      submission_type: 'full_audit',
    },
  },
  {
    id: 'event-northstar-email',
    lead_id: 'lead-northstar',
    created_at: '2026-07-07T07:24:00.000Z',
    event_type: 'email_clicked',
    source: 'audit_success',
    metadata: { cta_label: 'Reply to audit' },
  },
  {
    id: 'event-aurora-audit',
    lead_id: 'lead-aurora',
    created_at: '2026-07-06T15:45:00.000Z',
    event_type: 'audit_submitted',
    source: 'navbar_audit',
    metadata: {
      project_type: 'Client portal and onboarding',
      submission_type: 'full_audit',
    },
  },
  {
    id: 'event-aurora-schedule',
    lead_id: 'lead-aurora',
    created_at: '2026-07-06T16:10:00.000Z',
    event_type: 'schedule_clicked',
    source: 'audit_success',
    metadata: { cta_label: 'Book a call' },
  },
  {
    id: 'event-aurora-status',
    lead_id: 'lead-aurora',
    created_at: '2026-07-06T17:02:00.000Z',
    event_type: 'status_changed',
    source: 'dashboard',
    metadata: { from: 'qualified', to: 'scheduled' },
  },
  {
    id: 'event-halo-quick',
    lead_id: 'lead-halo',
    created_at: '2026-07-05T10:14:00.000Z',
    event_type: 'quick_start_submitted',
    source: 'selected_work_card',
    metadata: {
      project_type: 'Inventory planning workflow',
      submission_type: 'quick_start',
    },
  },
  {
    id: 'event-sable-proposal',
    lead_id: 'lead-sable',
    created_at: '2026-07-06T16:11:00.000Z',
    event_type: 'proposal_sent',
    source: 'dashboard',
    metadata: { value: 145000 },
  },
  {
    id: 'event-civic-quick',
    lead_id: 'lead-civic',
    created_at: '2026-07-02T11:32:00.000Z',
    event_type: 'quick_start_submitted',
    source: 'pricing_page',
    metadata: {
      project_type: 'Grant reporting workflow',
      submission_type: 'quick_start',
    },
  },
];

export const leadNotes: LeadNote[] = [
  {
    id: 'note-aurora-1',
    lead_id: 'lead-aurora',
    created_at: '2026-07-06T17:05:00.000Z',
    created_by: 'Ines Parker',
    body: 'Discovery call booked. Ask about SOC expectations and how much onboarding content already exists.',
  },
  {
    id: 'note-sable-1',
    lead_id: 'lead-sable',
    created_at: '2026-07-06T16:12:00.000Z',
    created_by: 'Ava Sinclair',
    body: 'Proposal sent with phase one focused on clienteling, fulfillment visibility, and launch readiness.',
  },
  {
    id: 'note-meridian-1',
    lead_id: 'lead-meridian',
    created_at: '2026-07-04T12:40:00.000Z',
    created_by: 'Malik West',
    body: 'Contacted by email. Need a next step if no reply by Thursday morning.',
  },
];

export const dashboardMetrics: MetricSummary[] = [
  {
    key: 'new_leads',
    label: 'New leads',
    value: 9,
    trend: '+18%',
    trendDirection: 'up',
    note: 'Compared with prior period',
  },
  {
    key: 'qualified_leads',
    label: 'Qualified leads',
    value: 5,
    trend: '+2',
    trendDirection: 'up',
    note: 'Above the fit threshold',
  },
  {
    key: 'scheduled_calls',
    label: 'Scheduled calls',
    value: 3,
    trend: '+1',
    trendDirection: 'up',
    note: 'Discovery calls booked',
  },
  {
    key: 'awaiting_reply',
    label: 'Awaiting reply',
    value: 3,
    trend: '+2',
    trendDirection: 'down',
    note: 'New or qualified without contact',
  },
  {
    key: 'full_audit_submissions',
    label: 'Full audit submissions',
    value: 5,
    trend: '+24%',
    trendDirection: 'up',
    note: 'High intent audit depth',
  },
  {
    key: 'schedule_clicks',
    label: 'Schedule clicks',
    value: 18,
    trend: '+11%',
    trendDirection: 'up',
    note: 'Across audit and booking CTAs',
  },
];

export const pipelineStages: PipelineStageSummary[] = [
  { status: 'new', label: 'New', count: 1, value: '$38k', intent: 'primary' },
  {
    status: 'qualified',
    label: 'Qualified',
    count: 2,
    value: '$132k',
    intent: 'warm',
  },
  {
    status: 'contacted',
    label: 'Contacted',
    count: 1,
    value: '$58k',
    intent: 'violet',
  },
  {
    status: 'scheduled',
    label: 'Scheduled',
    count: 1,
    value: '$96k',
    intent: 'teal',
  },
  {
    status: 'proposal_ready',
    label: 'Proposal ready',
    count: 1,
    value: '$145k',
    intent: 'warm',
  },
  { status: 'won', label: 'Won', count: 1, value: '$168k', intent: 'teal' },
  {
    status: 'lost',
    label: 'Lost',
    count: 1,
    value: '$18k',
    intent: 'destructive',
  },
  {
    status: 'archived',
    label: 'Archived',
    count: 1,
    value: '$0',
    intent: 'neutral',
  },
];

export const funnelSteps: FunnelStepSummary[] = [
  {
    key: 'homepage_views',
    label: 'Homepage views',
    value: 2840,
    rate: 100,
    delta: '+9%',
  },
  {
    key: 'cta_clicks',
    label: 'CTA clicks',
    value: 416,
    rate: 14.6,
    delta: '+13%',
  },
  {
    key: 'quick_start_submissions',
    label: 'Quick-start submissions',
    value: 74,
    rate: 17.8,
    delta: '+8%',
  },
  {
    key: 'full_audit_starts',
    label: 'Full audit starts',
    value: 46,
    rate: 62.1,
    delta: '+4%',
  },
  {
    key: 'full_audit_submissions',
    label: 'Full audit submissions',
    value: 29,
    rate: 63,
    delta: '+24%',
  },
  {
    key: 'schedule_clicks',
    label: 'Schedule clicks',
    value: 18,
    rate: 62.1,
    delta: '+11%',
  },
  {
    key: 'email_clicks',
    label: 'Email clicks',
    value: 12,
    rate: 41.4,
    delta: '+5%',
  },
  {
    key: 'selected_work_clicks',
    label: 'Selected Work clicks',
    value: 88,
    rate: 21.2,
    delta: '+16%',
  },
];

export const topRoutes: SourceSummary[] = [
  {
    key: '/',
    label: 'Homepage',
    value: 2840,
    context: 'Primary funnel entry',
    trend: '+9%',
  },
  {
    key: '/audit',
    label: 'Audit funnel',
    value: 1120,
    context: 'Highest intent route',
    trend: '+17%',
  },
  {
    key: '/selected-work',
    label: 'Selected Work',
    value: 720,
    context: 'Case study proof path',
    trend: '+14%',
  },
  {
    key: '/book-call',
    label: 'Book Call',
    value: 388,
    context: 'Direct booking path',
    trend: '+6%',
  },
];

export const topCtaSources: SourceSummary[] = [
  {
    key: 'home_hero_form',
    label: 'Home hero form',
    value: 126,
    context: '42% qualified rate',
    trend: '+18%',
  },
  {
    key: 'navbar_audit',
    label: 'Navbar audit',
    value: 92,
    context: 'Strong repeat visitor signal',
    trend: '+11%',
  },
  {
    key: 'selected_work_card',
    label: 'Selected Work card',
    value: 64,
    context: 'Best proof-driven source',
    trend: '+21%',
  },
  {
    key: 'book_call_page',
    label: 'Book Call page',
    value: 48,
    context: 'Highest schedule intent',
    trend: '+6%',
  },
];

export const topUtmCampaigns: SourceSummary[] = [
  {
    key: 'ops-audit-july',
    label: 'ops-audit-july',
    value: 38,
    context: '7 full audits',
    trend: '+15%',
  },
  {
    key: 'founder-systems',
    label: 'founder-systems',
    value: 26,
    context: '5 qualified leads',
    trend: '+8%',
  },
  {
    key: 'selected-work-retargeting',
    label: 'selected-work-retargeting',
    value: 19,
    context: '2 scheduled calls',
    trend: '+12%',
  },
];

export const topReferrers: SourceSummary[] = [
  {
    key: 'linkedin',
    label: 'LinkedIn',
    value: 410,
    context: 'Founder audience',
    trend: '+12%',
  },
  {
    key: 'direct',
    label: 'Direct',
    value: 392,
    context: 'Brand demand',
    trend: '+7%',
  },
  {
    key: 'newsletter',
    label: 'Operator newsletter',
    value: 188,
    context: 'Warm traffic',
    trend: '+19%',
  },
];

export const deviceCategories: SourceSummary[] = [
  {
    key: 'desktop',
    label: 'Desktop',
    value: 64,
    context: 'Best conversion depth',
  },
  { key: 'mobile', label: 'Mobile', value: 29, context: 'High audit starts' },
  {
    key: 'tablet',
    label: 'Tablet',
    value: 7,
    context: 'Mostly returning visitors',
  },
];

export const dailyVisitors: SourceSummary[] = [
  { key: 'Jul 1', label: 'Jul 1', value: 342, context: '4.6% conversion' },
  { key: 'Jul 2', label: 'Jul 2', value: 388, context: '4.9% conversion' },
  { key: 'Jul 3', label: 'Jul 3', value: 404, context: '5.2% conversion' },
  { key: 'Jul 4', label: 'Jul 4', value: 361, context: '4.1% conversion' },
  { key: 'Jul 5', label: 'Jul 5', value: 427, context: '5.7% conversion' },
  { key: 'Jul 6', label: 'Jul 6', value: 486, context: '6.1% conversion' },
  { key: 'Jul 7', label: 'Jul 7', value: 432, context: '5.8% conversion' },
];

export const dailySubmissions: SourceSummary[] = [
  { key: 'Jul 1', label: 'Jul 1', value: 7, context: '2 full audits' },
  { key: 'Jul 2', label: 'Jul 2', value: 9, context: '1 full audit' },
  { key: 'Jul 3', label: 'Jul 3', value: 11, context: '4 full audits' },
  { key: 'Jul 4', label: 'Jul 4', value: 6, context: '1 full audit' },
  { key: 'Jul 5', label: 'Jul 5', value: 14, context: '5 full audits' },
  { key: 'Jul 6', label: 'Jul 6', value: 17, context: '7 full audits' },
  { key: 'Jul 7', label: 'Jul 7', value: 10, context: '3 full audits' },
];

export const dailyScheduleClicks: SourceSummary[] = [
  { key: 'Jul 1', label: 'Jul 1', value: 2, context: 'Audit success' },
  { key: 'Jul 2', label: 'Jul 2', value: 1, context: 'Book Call page' },
  { key: 'Jul 3', label: 'Jul 3', value: 4, context: 'Audit success' },
  { key: 'Jul 4', label: 'Jul 4', value: 2, context: 'Home hero schedule' },
  { key: 'Jul 5', label: 'Jul 5', value: 3, context: 'Selected Work' },
  { key: 'Jul 6', label: 'Jul 6', value: 5, context: 'Audit success' },
  { key: 'Jul 7', label: 'Jul 7', value: 1, context: 'Navbar audit' },
];

export const dailyConversionRate: SourceSummary[] = [
  { key: 'Jul 1', label: 'Jul 1', value: 4.6, context: 'Visitor to lead' },
  { key: 'Jul 2', label: 'Jul 2', value: 4.9, context: 'Visitor to lead' },
  { key: 'Jul 3', label: 'Jul 3', value: 5.2, context: 'Visitor to lead' },
  { key: 'Jul 4', label: 'Jul 4', value: 4.1, context: 'Visitor to lead' },
  { key: 'Jul 5', label: 'Jul 5', value: 5.7, context: 'Visitor to lead' },
  { key: 'Jul 6', label: 'Jul 6', value: 6.1, context: 'Visitor to lead' },
  { key: 'Jul 7', label: 'Jul 7', value: 5.8, context: 'Visitor to lead' },
];

export const submissionsByProjectType: SourceSummary[] = [
  {
    key: 'revenue_ops',
    label: 'Revenue operations',
    value: 18,
    context: 'Highest fit scores',
  },
  {
    key: 'portal',
    label: 'Portal and onboarding',
    value: 14,
    context: 'High enterprise intent',
  },
  {
    key: 'commerce_ops',
    label: 'Commerce operations',
    value: 11,
    context: 'Premium segment',
  },
  {
    key: 'reporting',
    label: 'Reporting workflow',
    value: 9,
    context: 'Clear scope',
  },
];

export const submissionsByIndustry: SourceSummary[] = [
  {
    key: 'b2b_services',
    label: 'B2B services',
    value: 22,
    context: 'Founder-led operators',
  },
  { key: 'fintech', label: 'Fintech', value: 13, context: 'Portal demand' },
  {
    key: 'healthcare',
    label: 'Healthcare services',
    value: 9,
    context: 'Scheduling pressure',
  },
  {
    key: 'luxury_retail',
    label: 'Luxury retail',
    value: 7,
    context: 'High value workflows',
  },
];

export const submissionsByBudget: SourceSummary[] = [
  {
    key: '$25k-$45k',
    label: '$25k to $45k',
    value: 18,
    context: 'Scoped repair work',
  },
  {
    key: '$45k-$75k',
    label: '$45k to $75k',
    value: 16,
    context: 'Core Luxa fit',
  },
  {
    key: '$75k-$120k',
    label: '$75k to $120k',
    value: 9,
    context: 'Platform build interest',
  },
  {
    key: '$120k+',
    label: '$120k plus',
    value: 6,
    context: 'Strategic build segment',
  },
];

export const submissionsByTimeline: SourceSummary[] = [
  {
    key: '30-60',
    label: '30 to 60 days',
    value: 17,
    context: 'Fastest follow-up',
  },
  {
    key: 'quarter',
    label: 'This quarter',
    value: 15,
    context: 'Best proposal fit',
  },
  {
    key: '60-90',
    label: '60 to 90 days',
    value: 11,
    context: 'Discovery needed',
  },
  {
    key: 'later',
    label: 'Later this year',
    value: 6,
    context: 'Nurture segment',
  },
];

export const analyticsMetrics: MetricSummary[] = [
  {
    key: 'visitors',
    label: 'Visitors',
    value: '2,840',
    trend: '+9%',
    trendDirection: 'up',
    note: 'Unique visitors',
  },
  {
    key: 'cta_clicks',
    label: 'CTA clicks',
    value: 416,
    trend: '+13%',
    trendDirection: 'up',
    note: 'Allowed source data only',
  },
  {
    key: 'quick_start_submissions',
    label: 'Quick-start submissions',
    value: 74,
    trend: '+8%',
    trendDirection: 'up',
    note: 'Short form intent',
  },
  {
    key: 'full_audit_submissions',
    label: 'Full audit submissions',
    value: 29,
    trend: '+24%',
    trendDirection: 'up',
    note: 'High intent conversions',
  },
  {
    key: 'schedule_clicks',
    label: 'Schedule clicks',
    value: 18,
    trend: '+11%',
    trendDirection: 'up',
    note: 'Booking intent',
  },
  {
    key: 'email_clicks',
    label: 'Email clicks',
    value: 12,
    trend: '+5%',
    trendDirection: 'up',
    note: 'Direct reply intent',
  },
];

export const analyticsSummary: AnalyticsSummary = {
  dateRange: defaultDashboardDateRange,
  metrics: analyticsMetrics,
  funnel: funnelSteps.slice(0, 6),
  dailyVisitors,
  dailySubmissions,
  dailyScheduleClicks,
  dailyConversionRate,
  ctaClicksBySource: topCtaSources,
  submissionsByProjectType,
  submissionsByIndustry,
  submissionsByBudget,
  submissionsByTimeline,
  topLandingPages: topRoutes,
  topReferrers,
  utmCampaignPerformance: topUtmCampaigns,
  source: 'mock',
};
